### ISSUE TITLE
Unable to submit package

### ISSUE THREAD

**Issue by rmetzger** [ververica/flink-ecosystem#80]
![Screenshot 2019-11-14 08 50 40](https://user-images.githubusercontent.com/89049/68836993-ee024a80-06bb-11ea-9ba3-6f1dc6ba5fcb.png)

This is the description text
```
This connector (https://cn.aliyun.com/product/sls)

行业领先的日志大数据解决方案，一站式提供数据收集、清洗、分析、可视化和告警功能。
全面提升海量日志处理能力，实时挖掘数据价值，智能助力研发/运维/运营/安全等场景。
```

This is the error message I see from the server
```
server listening on port 4000

  InternalServerError: an unknown error has occured
      at Object.throw (/node/node_modules/koa/lib/context.js:97:11)
      at _599‍.r.exports.post (/node/src/server/routes/api/v1/packages/index.js:107:27)


  InternalServerError: an unknown error has occured
      at Object.throw (/node/node_modules/koa/lib/context.js:97:11)
      at _599‍.r.exports.post (/node/src/server/routes/api/v1/packages/index.js:107:27)

```

**Comment by rmetzger** [comment]
I might be able to fix this myself
```
Caught exception { Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xE8\xA1\x8C\xE4\xB8\x9A...' for column `flink_ecosystem`.`package`.`readme` at row 1
    at Query.Sequence._packetToError (/node/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/node/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/node/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/node/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/node/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/node/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/node/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/node/node_modules/mysql/lib/Connection.js:525:10)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    --------------------
    at Protocol._enqueue (/node/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/node/node_modules/mysql/lib/Connection.js:201:25)
    at /node/node_modules/knex/lib/dialects/mysql/index.js:130:18
    at Promise._execute (/node/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/node/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/node/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/node/node_modules/knex/lib/dialects/mysql/index.js:124:12)
    at Client_MySQL.query (/node/node_modules/knex/lib/client.js:158:17)
    at Runner.query (/node/node_modules/knex/lib/runner.js:135:36)
    at /node/node_modules/knex/lib/runner.js:39:23
    at tryCatcher (/node/node_modules/bluebird/js/release/util.js:16:23)
    at /node/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/node/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/node/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/node/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/node/node_modules/bluebird/js/release/promise.js:619:10)
  code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
  errno: 1366,
  sqlMessage:
   'Incorrect string value: \'\\xE8\\xA1\\x8C\\xE4\\xB8\\x9A...\' for column `flink_ecosystem`.`package`.`readme` at row 1',
  sqlState: '22007',
  index: 0,
  sql:
   'insert into `package` (`added`, `category`, `description`, `image_id`, `license`, `name`, `readme`, `repository`, `slug`, `tags`, `updated`, `user_id`, `website`) values (now(), \'connectors\', \'ali test\', 0, \'Apache 2.0\', \'ali test\', \'This connector (https://cn.aliyun.com/product/sls)\\n\\n行业领先的日志大数据解决方案，一站式提供数据收集、清洗、分析、可视化和告警功能。\\n全面提升海量日志处理能力，实时挖掘数据价值，智能助力研发/运维/运营/安全等场景。\', \'https://cn.aliyun.com/product/sls\', \'ali-test\', \'\', now(), 89049, \'https://cn.aliyun.com/product/sls\')' }

  InternalServerError: an unknown error has occured
      at Object.throw (/node/node_modules/koa/lib/context.js:97:11)
      at _689‍.r.exports.post (/node/src/server/routes/api/v1/packages/index.js:108:37)
```
